#!/usr/bin/env bash
set -euo pipefail
set -x

MODEL_PATH="${MODEL_PATH:-Qwen/Qwen2.5-Math-7B}"
TRAIN_FILE="${TRAIN_FILE:?Set TRAIN_FILE to a Scaf-GRPO training parquet}"
VAL_FILE="${VAL_FILE:-${TRAIN_FILE}}"
OUTPUT_DIR="${OUTPUT_DIR:-outputs/scaf_grpo_qwen2_5_math_7b}"

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    algorithm.use_kl_in_reward=false \
    data.train_files="${TRAIN_FILE}" \
    data.val_files="${VAL_FILE}" \
    data.train_batch_size=256 \
    data.val_batch_size=512 \
    data.max_prompt_length=4096 \
    data.max_response_length=4096 \
    data.filter_overlong_prompts=true \
    data.truncation=error \
    data.shuffle=true \
    data.seed=42 \
    actor_rollout_ref.model.path="${MODEL_PATH}" \
    actor_rollout_ref.model.enable_gradient_checkpointing=true \
    actor_rollout_ref.model.use_remove_padding=true \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.actor.use_kl_loss=false \
    actor_rollout_ref.actor.use_off_policy_loss=true \
    actor_rollout_ref.actor.off_policy_loss_impl=token \
    actor_rollout_ref.actor.off_policy_cliprange=0.2 \
    actor_rollout_ref.actor.off_policy_normalize=false \
    actor_rollout_ref.actor.use_off_policy_probs=false \
    actor_rollout_ref.actor.use_off_policy_clip=false \
    actor_rollout_ref.actor.off_policy_max_clip=-1 \
    actor_rollout_ref.actor.off_policy_min_clip=-1 \
    actor_rollout_ref.actor.off_policy_reshape=p_div_p_0.1 \
    actor_rollout_ref.actor.off_policy_reshape_weight=0.1 \
    actor_rollout_ref.actor.off_policy_reshape_pow_exp=0.5 \
    actor_rollout_ref.actor.on_policy_reshape=no_reshape \
    actor_rollout_ref.actor.on_policy_reshape_weight=0.1 \
    actor_rollout_ref.actor.on_policy_reshape_pow_exp=0.5 \
    actor_rollout_ref.actor.clip_upper_bound=1.0 \
    actor_rollout_ref.actor.all_max_clip=-1 \
    actor_rollout_ref.actor.loss_remove_token_mean=true \
    actor_rollout_ref.actor.loss_remove_clip=true \
    actor_rollout_ref.actor.use_ppo_kl_loss=false \
    actor_rollout_ref.actor.ppo_kl_loss_coef=0.01 \
    actor_rollout_ref.actor.entropy_coeff=0.001 \
    algorithm.norm_adv_by_std_in_grpo=false \
    actor_rollout_ref.actor.fsdp_config.param_offload=false \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=false \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.rollout.temperature=1.0 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
    actor_rollout_ref.rollout.enable_chunked_prefill=true \
    actor_rollout_ref.rollout.max_num_batched_tokens=32768 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.ref.fsdp_config.param_offload=true \
    reward_manager.name=naive \
    reward_model.reward_manager=remote \
    reward_model.num_workers=1 \
    reward_model.launch_reward_fn_async=false \
    trainer.with_hint=true \
    trainer.with_luffy_expert=true \
    trainer.luffy_expert_every_group=false \
    trainer.luffy_expert_key=qwen_expert_trajectory \
    trainer.warmup_steps=50 \
    trainer.replace_hint_prompt=false \
    trainer.replace_num=1 \
    trainer.scaf_hint_stages=3 \
    trainer.hint_data_dir="${OUTPUT_DIR}/hint_rollouts" \
    trainer.rollout_data_dir="${OUTPUT_DIR}/rollouts" \
    trainer.validation_data_dir="${OUTPUT_DIR}/validation" \
    trainer.default_local_dir="${OUTPUT_DIR}/checkpoints" \
    trainer.project_name=scaf_grpo \
    trainer.experiment_name=qwen2_5_math_7b \
    trainer.logger='["console","wandb","tensorboard"]' \
    trainer.tracking_dir="${OUTPUT_DIR}" \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=10 \
    trainer.test_freq=10 \
    trainer.val_before_train=false \
    trainer.total_epochs=100 \
    "$@"
